### ISSUE TITLE
UE log viewer

### ISSUE THREAD

**Issue by rijilrose** [LanternD/Quectel-debug-log-decoder#1]
I am using BG96 quectel board,

When I run the executable

Could not find file

Neul\Decoders\messages.xml

Application is shutdown now
<img width="307" alt="UELogviewerIssue" src="https://user-images.githubusercontent.com/65706664/99346919-c2600480-28bb-11eb-999c-b681107978f1.png">

**Comment by LanternD** [comment]
BG96 does not have a corresponding `message.xml`, so it is not possible to read the debug logs from it using this software. You may want to take a look at QXDM by Qualcomm.

Only Quectel BC28, BC35, BC95 have `message.xml`.
